build:
    dependencies:
        before:
            - mkdir -p ~/artifacts/coverage
    environment:
        php:
            version: 5.6.0
    tests:
        override:
            -
                command: make scrutinizer-test SUITE=unit
                coverage:
                    file: ~/artifacts/coverage/unit.xml
                    format: php-clover
filter:
    paths:
        - src/*
        - dev/*
checks:
    php:
        uppercase_constants: true
        return_doc_comments: true
        parameter_doc_comments: true
        more_specific_types_in_doc_comments: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        classes_in_camel_caps: true
        encourage_single_quotes: true
        fix_doc_comments: false

coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            before_parentheses:
                function_declaration: true
                closure_definition: true
            around_operators:
                concatenation: false
                negation: true
            within:
                brackets: true
                array_initializer: true
                grouping: true
                function_call: true
                function_declaration: true
                if: true
                for: true
                while: true
                switch: true
                catch: true
        braces:
            classes_functions:
                class: end-of-line
                function: new-line
                closure: new-line
            if:
                opening: new-line
                else_on_new_line: true
            for:
                opening: new-line
            switch:
                opening: new-line
            try:
                opening: new-line
                catch_on_new_line: true
                finally_on_new_line: true
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

